# Generated by Django 6.0.8 on 2026-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0023_resource_settings_display_rules_initialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpathprofile',
            name='match_rules',
            field=models.JSONField(blank=True, default=list, help_text='支持 fm / fm_timestamp / archive / executor_tree / run_flat；executor_tree 表示执行器根目录/IP/子系统/任意日志，run_flat 表示运行日志根目录下 event.log/归档。', verbose_name='文件匹配规则'),
        ),
    ]
