# Generated by Django 6.0.8 on 2026-09-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0024_alter_logpathprofile_match_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, verbose_name='收藏'),
        ),
    ]
