# Generated by Django 6.0.8 on 2026-09-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0025_environment_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='is_favorite',
        ),
    ]
