# Generated by Django 6.0.8 on 2026-09-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUiReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=96, unique=True)),
                ('receipt', models.JSONField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.agenttask')),
            ],
        ),
    ]
