# Generated by Django 6.0.8 on 2026-09-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0024_alter_logpathprofile_match_rules'),
        ('logsources', '0013_merge_event_components_into_modules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logresourcecatalog',
            options={'ordering': ['environment', 'source_category', 'machine', 'root'], 'verbose_name': '环境日志资源扫描记录', 'verbose_name_plural': '环境日志资源扫描记录'},
        ),
        migrations.AlterModelOptions(
            name='logresourcecatalogitem',
            options={'ordering': ['subsystem', 'fm'], 'verbose_name': '环境日志资源发现项', 'verbose_name_plural': '环境日志资源发现项'},
        ),
        migrations.AlterField(
            model_name='logresourcecatalogitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logsources.logresourcecatalog', verbose_name='资源扫描记录'),
        ),
        migrations.CreateModel(
            name='LogWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, verbose_name='监控名称')),
                ('source_rule_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='来源语义规则ID')),
                ('level', models.CharField(choices=[('observe', '只观察（时间线打标）'), ('capture', '采集数据'), ('alert', '告警通知')], default='observe', max_length=16, verbose_name='级别')),
                ('trigger_kind', models.CharField(choices=[('appear', '出现即命中'), ('burst', '窗口内出现 N 次'), ('silence', '静默（应有日志却没有）')], default='appear', max_length=16, verbose_name='触发方式')),
                ('trigger_config', models.JSONField(blank=True, default=dict, verbose_name='触发参数')),
                ('targets', models.JSONField(blank=True, default=list, verbose_name='监听目标')),
                ('source_categories', models.JSONField(blank=True, default=list, verbose_name='日志类型')),
                ('capture_config', models.JSONField(blank=True, default=dict, verbose_name='采集参数')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='创建人')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='最近命中')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='命中次数')),
                ('dropped_count', models.PositiveIntegerField(default=0, verbose_name='因配额丢弃')),
                ('last_error', models.TextField(blank=True, verbose_name='最近错误')),
                ('last_worker_id', models.CharField(blank=True, max_length=64, verbose_name='当前持有worker')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='worker心跳')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_watches', to='environments.environment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '日志监控',
                'verbose_name_plural': '日志监控',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogWatchHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('seq', models.BigIntegerField(db_index=True, verbose_name='序号')),
                ('matched_at', models.DateTimeField(db_index=True, verbose_name='命中时间')),
                ('signature', models.CharField(db_index=True, max_length=255, verbose_name='归一化签名')),
                ('level', models.CharField(blank=True, max_length=16, verbose_name='日志级别')),
                ('machine', models.CharField(blank=True, max_length=128, verbose_name='机器')),
                ('subsystem', models.CharField(blank=True, max_length=128, verbose_name='子系统')),
                ('fm', models.CharField(blank=True, max_length=128, verbose_name='模块')),
                ('source_path', models.CharField(blank=True, max_length=512, verbose_name='来源文件')),
                ('source_category', models.CharField(blank=True, max_length=32, verbose_name='日志类型')),
                ('line_text', models.TextField(blank=True, verbose_name='命中原文')),
                ('window_lines', models.JSONField(blank=True, default=list, verbose_name='采集窗口')),
                ('extracted', models.JSONField(blank=True, default=dict, verbose_name='提取字段')),
                ('dedup_key', models.CharField(max_length=64, unique=True, verbose_name='去重键')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='logsources.logwatch', verbose_name='监控')),
            ],
            options={
                'verbose_name': '日志监控命中',
                'verbose_name_plural': '日志监控命中',
                'ordering': ['-seq'],
            },
        ),
        migrations.AddIndex(
            model_name='logwatch',
            index=models.Index(fields=['enabled', 'environment'], name='logwatch_enabled_env_idx'),
        ),
        migrations.AddConstraint(
            model_name='logwatch',
            constraint=models.UniqueConstraint(fields=('environment', 'name'), name='uniq_log_watch_environment_name'),
        ),
        migrations.AddIndex(
            model_name='logwatchhit',
            index=models.Index(fields=['watch', '-seq'], name='logwatchhit_watch_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='logwatchhit',
            index=models.Index(fields=['watch', 'signature', 'matched_at'], name='logwatchhit_sig_time_idx'),
        ),
    ]
