# Generated by Django 6.0.8 on 2026-09-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logsources', '0014_alter_logresourcecatalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logwatch',
            name='extraction_rule_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='来源数据提取器ID'),
        ),
    ]
