# Generated by Django 6.0.8 on 2026-09-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_logsearchaudit_diagnostics'),
        ('environments', '0025_environment_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataextractionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dataextractionrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='OperationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation_id', models.CharField(db_index=True, max_length=128, verbose_name='操作ID')),
                ('operator_username', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='操作用户')),
                ('client_ip', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='操作IP')),
                ('trigger', models.CharField(choices=[('user', '用户操作'), ('ai', 'AI 代操作'), ('system', '系统自动')], db_index=True, default='user', max_length=16, verbose_name='发起方')),
                ('feature_group', models.CharField(db_index=True, max_length=64, verbose_name='功能分组')),
                ('feature_name', models.CharField(db_index=True, max_length=128, verbose_name='功能名')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='操作记录')),
                ('environment_name', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='环境名称快照')),
                ('target_kind', models.CharField(blank=True, max_length=32, verbose_name='目标类型')),
                ('target_name', models.CharField(blank=True, max_length=255, verbose_name='目标名称')),
                ('http_method', models.CharField(max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, max_length=512, verbose_name='接口路径')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='响应状态码')),
                ('outcome', models.CharField(choices=[('success', '成功'), ('failed', '失败')], db_index=True, default='success', max_length=16, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='请求参数（已脱敏）')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_audits', to='environments.environment', verbose_name='目标环境')),
                ('log_search_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_audits', to='audits.logsearchaudit', verbose_name='关联日志检索审计')),
            ],
            options={
                'verbose_name': '操作审计',
                'verbose_name_plural': '操作审计',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at', 'outcome'], name='op_audit_time_result_idx'), models.Index(fields=['feature_group', '-created_at'], name='op_audit_group_time_idx'), models.Index(fields=['client_ip', '-created_at'], name='op_audit_ip_time_idx'), models.Index(fields=['operator_username', '-created_at'], name='op_audit_user_time_idx')],
            },
        ),
    ]
