# Generated by Django 6.0.8 on 2026-09-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_operationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationaudit',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='浏览器会话'),
        ),
    ]
